version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/warp
    runas: ubuntu
hooks:
  AfterInstall:
    - location: scripts/run_semantic_tests.sh
      timeout: 3600
      runas: codedeployuser
