version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - pip install poetry
      - poetry run make test_semantics
  post_build:
    commands:
      - echo Build completed on `date`
