version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y python3.7-dev libfmt-dev
  build:
    commands:
      - pip install poetry
      - poetry run make test_semantics
  post_build:
    commands:
      - echo Build completed on `date`
